ifndef ROLLCOMPILER
  ROLLCOMPILER = gnu
endif
COMPILERNAME := $(firstword $(subst /, ,$(ROLLCOMPILER)))

ifndef ROLLMPI
  ROLLMPI = rocks-openmpi
endif
MPINAME := $(firstword $(subst /, ,$(ROLLMPI)))

NAME           = sdsc-ncl_ncarg
VERSION        = 6.3.0
RELEASE        = 0
PKGROOT        = /opt/ncl_ncarg

SRC_SUBDIR     = ncl_ncarg

SOURCE_NAME    = ncl_ncarg
SOURCE_SUFFIX  = tar.gz
SOURCE_VERSION = $(VERSION)
SOURCE_PKG     = $(SOURCE_NAME)-$(SOURCE_VERSION).$(SOURCE_SUFFIX)
SOURCE_DIR     = $(SOURCE_NAME)-$(VERSION)

SZIP_SOURCE_NAME    = szip
SZIP_SOURCE_SUFFIX  = tar.gz
SZIP_SOURCE_VERSION = 2.1
SZIP_SOURCE_PKG     = $(SZIP_SOURCE_NAME)-$(SZIP_SOURCE_VERSION).$(SZIP_SOURCE_SUFFIX)
SZIP_SOURCE_DIR     = $(SZIP_SOURCE_NAME)-$(SZIP_SOURCE_VERSION)

ZLIB_SOURCE_NAME    = zlib
ZLIB_SOURCE_SUFFIX  = tar.gz
ZLIB_SOURCE_VERSION = 1.2.8
ZLIB_SOURCE_PKG     = $(ZLIB_SOURCE_NAME)-$(ZLIB_SOURCE_VERSION).$(ZLIB_SOURCE_SUFFIX)
ZLIB_SOURCE_DIR     = $(ZLIB_SOURCE_NAME)-$(ZLIB_SOURCE_VERSION)

HDF4_SOURCE_NAME    = hdf-4
HDF4_SOURCE_SUFFIX  = tar.bz2
HDF4_SOURCE_VERSION = 2.11
HDF4_SOURCE_PKG     = $(HDF4_SOURCE_NAME).$(HDF4_SOURCE_VERSION).$(HDF4_SOURCE_SUFFIX)
HDF4_SOURCE_DIR     = $(HDF4_SOURCE_NAME).$(HDF4_SOURCE_VERSION)

CAIRO_SOURCE_NAME    = cairo
CAIRO_SOURCE_SUFFIX  = tar.gz
CAIRO_SOURCE_VERSION = 1.14.6
CAIRO_SOURCE_PKG     = $(CAIRO_SOURCE_NAME)-$(CAIRO_SOURCE_VERSION).$(CAIRO_SOURCE_SUFFIX)
CAIRO_SOURCE_DIR     = $(CAIRO_SOURCE_NAME)-$(CAIRO_SOURCE_VERSION)

HDFEOS5_SOURCE_NAME    = hdfeos5
HDFEOS5_SOURCE_SUFFIX  = tar.gz
HDFEOS5_SOURCE_VERSION = 1.15
HDFEOS5_SOURCE_PKG     = $(HDFEOS5_SOURCE_NAME)-$(HDFEOS5_SOURCE_VERSION).$(HDFEOS5_SOURCE_SUFFIX)
HDFEOS5_SOURCE_DIR     = $(HDFEOS5_SOURCE_NAME)-$(HDFEOS5_SOURCE_VERSION)

TAR_GZ_PKGS       = $(SOURCE_PKG) $(SZIP_SOURCE_PKG) $(CAIRO_SOURCE_PKG) $(ZLIB_SOURCE_PKG) $(HDFEOS5_SOURCE_PKG)
TAR_BZ2_PKGS      = $(HDF4_SOURCE_PKG)

RPM.EXTRAS     = AutoReq:No
